#!/usr/bin/env python3
"""Generate provenance-preserving official DeepSeek Harness design tokens."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


GENERATOR_NAME = "generate_official_theme_tokens.py"
GENERATOR_VERSION = "1.0.0"
EXPECTED_COMMIT = "141eb6fef83422698aef7a981029e843e8161534"
THEME_PATH = Path("packages/client/ui-theme/src/styles/design-platform.css")
DECLARATION = re.compile(r"^\s*(--dsw-[\w-]+)\s*:\s*([^;]+);\s*$")
VAR = re.compile(r"var\((--dsw-[\w-]+)\)")
RGB = re.compile(r"^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$")
RGBA = re.compile(r"^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)$")


@dataclass(frozen=True)
class Declaration:
    css_name: str
    raw_value: str
    line: int
    scheme: str


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--official-root", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--swift-output", type=Path, required=True)
    return parser.parse_args()


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def parse(root: Path) -> tuple[dict[str, Declaration], dict[str, Declaration], bytes]:
    path = root / THEME_PATH
    contents = path.read_bytes()
    lines = contents.decode("utf-8").splitlines()
    light: dict[str, Declaration] = {}
    dark: dict[str, Declaration] = {}
    scheme = "light"
    for line_number, line in enumerate(lines, start=1):
        if "body[data-ds-dark-theme]" in line:
            scheme = "dark"
        elif line.strip() == "body {":
            scheme = "light"
        match = DECLARATION.match(line)
        if match is None:
            continue
        declaration = Declaration(match.group(1), match.group(2).strip(), line_number, scheme)
        (dark if scheme == "dark" else light)[declaration.css_name] = declaration
    if not light or not dark:
        raise ValueError("expected light and dark --dsw-* declarations")
    return light, dark, contents


def rgba(value: str) -> dict[str, float] | None:
    rgb = RGB.fullmatch(value)
    if rgb:
        return {"red": int(rgb.group(1)) / 255, "green": int(rgb.group(2)) / 255, "blue": int(rgb.group(3)) / 255, "alpha": 1}
    rgba_match = RGBA.fullmatch(value)
    if rgba_match:
        return {
            "red": int(rgba_match.group(1)) / 255,
            "green": int(rgba_match.group(2)) / 255,
            "blue": int(rgba_match.group(3)) / 255,
            "alpha": float(rgba_match.group(4)),
        }
    return None


def resolve(name: str, declarations: dict[str, Declaration], stack: tuple[str, ...] = ()) -> tuple[str, dict[str, float] | None]:
    if name in stack:
        raise ValueError("cyclic CSS variable: " + " -> ".join((*stack, name)))
    declaration = declarations.get(name)
    if declaration is None:
        raise ValueError(f"unresolved CSS variable {name}")
    variable = VAR.fullmatch(declaration.raw_value)
    if variable:
        return resolve(variable.group(1), declarations, (*stack, name))
    return declaration.raw_value, rgba(declaration.raw_value)


def swift_identifier(css_name: str) -> str:
    words = css_name.removeprefix("--dsw-").replace("-", " ").split()
    return words[0] + "".join(word.capitalize() for word in words[1:])


def swift_rgba(value: dict[str, float]) -> str:
    return (
        "OfficialRGBA("
        f"red: {repr(value['red'])}, "
        f"green: {repr(value['green'])}, "
        f"blue: {repr(value['blue'])}, "
        f"alpha: {repr(value['alpha'])}"
        ")"
    )


def swift_source(tokens: list[dict[str, object]], commit: str, revision: str, source_input_revision: str) -> str:
    literals: list[str] = []
    properties: list[str] = []
    for token in tokens:
        name = str(token["cssName"])
        identifier = swift_identifier(name)
        light = token["light"]["resolvedRGBA"]
        dark = token["dark"]["resolvedRGBA"]
        if light is None or dark is None:
            continue
        literals.append(
            f'        "{name}": OfficialColorToken(cssName: "{name}", light: {swift_rgba(light)}, dark: {swift_rgba(dark)})'
        )
        properties.append(f'    static let {identifier} = value("{name}")')
    values = ",\n".join(literals)
    accessors = "\n".join(properties)
    return f'''// Generated by {GENERATOR_NAME} {GENERATOR_VERSION}; do not edit.\nimport AppKit\nimport SwiftUI\n\nstruct OfficialRGBA: Hashable, Sendable {{\n    let red: Double\n    let green: Double\n    let blue: Double\n    let alpha: Double\n\n    func color(for scheme: ColorScheme) -> Color {{\n        Color(red: red, green: green, blue: blue, opacity: alpha)\n    }}\n}}\n\nstruct OfficialColorToken: Hashable, Sendable {{\n    let cssName: String\n    let light: OfficialRGBA\n    let dark: OfficialRGBA\n\n    func color(for scheme: ColorScheme) -> Color {{\n        (scheme == .dark ? dark : light).color(for: scheme)\n    }}\n\n    var lightColor: Color {{ light.color(for: .light) }}\n    var darkColor: Color {{ dark.color(for: .dark) }}\n\n    var adaptiveColor: Color {{\n        Color(NSColor(name: nil) {{ appearance in\n            let isDark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua\n            let value = isDark ? dark : light\n            return NSColor(srgbRed: value.red, green: value.green, blue: value.blue, alpha: value.alpha)\n        }})\n    }}\n}}\n\nextension OfficialUISpec {{\n    enum Theme {{\n        static let sourceCommit = "{commit}"\n        static let revision = "{revision}"
        static let sourceInputRevision = "{source_input_revision}"
        static let colorTokens: [String: OfficialColorToken] = [\n{values}\n        ]\n\n        static func value(_ cssName: String) -> OfficialColorToken {{\n            guard let token = colorTokens[cssName] else {{\n                preconditionFailure("Unknown official color token: \\(cssName)")\n            }}\n            return token\n        }}\n\n{accessors}\n    }}\n}}\n'''


def main() -> None:
    args = arguments()
    root = args.official_root.resolve()
    commit = git(root, "rev-parse", "HEAD")
    if commit != EXPECTED_COMMIT:
        raise SystemExit(f"official root must be {EXPECTED_COMMIT}, got {commit}")
    light, dark, contents = parse(root)
    names = sorted(set(light) | set(dark))
    tokens: list[dict[str, object]] = []
    for name in names:
        light_declaration = light.get(name)
        dark_declaration = dark.get(name, light_declaration)
        if light_declaration is None or dark_declaration is None:
            raise ValueError(f"missing color token scheme for {name}")
        light_resolved, light_rgba = resolve(name, light)
        dark_resolved, dark_rgba = resolve(name, {**light, **dark})
        tokens.append({
            "cssName": name,
            "light": {"rawValue": light_declaration.raw_value, "resolvedValue": light_resolved, "resolvedRGBA": light_rgba, "sourceLine": light_declaration.line},
            "dark": {"rawValue": dark_declaration.raw_value, "resolvedValue": dark_resolved, "resolvedRGBA": dark_rgba, "sourceLine": dark_declaration.line},
            "source": {"path": THEME_PATH.as_posix(), "commit": commit},
        })
    revision = "sha256:" + hashlib.sha256(contents).hexdigest()
    source_input_digest = hashlib.sha256()
    source_input_digest.update(THEME_PATH.as_posix().encode("utf-8"))
    source_input_digest.update(b"\0")
    source_input_digest.update(contents)
    source_input_revision = "sha256:" + source_input_digest.hexdigest()
    document = {
        "schemaVersion": 1,
        "sourceCommit": commit,
        "themeRevision": revision,
        "sourceInputRevision": source_input_revision,
        "generatedAt": git(root, "show", "-s", "--format=%cI", commit),
        "generator": {"name": GENERATOR_NAME, "version": GENERATOR_VERSION},
        "tokens": tokens,
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    args.swift_output.parent.mkdir(parents=True, exist_ok=True)
    args.swift_output.write_text(swift_source(tokens, commit, revision, source_input_revision), encoding="utf-8")
    print(f"Generated {len(tokens)} official color tokens from {THEME_PATH}.")


if __name__ == "__main__":
    main()
