#!/usr/bin/env python3
"""Generate deterministic OfficialUISpec build metadata from the locked upstream tree."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import subprocess
from pathlib import Path
from typing import Iterable


GENERATOR_NAME = "generate_official_ui_spec_build.py"
GENERATOR_VERSION = "1.0.0"
EXPECTED_COMMIT = "b150a551b8d465e31e418e1b2eaf5e79bbb7d28e"
HOST_BUILD_ID = "dsh-0.1.1-rc.2-official-b150a55"
UI_SPEC_REVISION = "official-b150a55-ui-spec-r1"


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--official-root", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--swift-output", type=Path, required=True)
    return parser.parse_args()


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def source_paths(root: Path) -> dict[str, list[Path]]:
    locale = sorted({
        *root.glob("packages/client/**/src/client/locales.ts"),
        *root.glob("packages/client/**/src/client/locale.ts"),
        *root.glob("packages/client/locale/src/locales/*.ts"),
        root / "packages/client/ui-settings-models/src/onboarding-copy.ts",
    })
    locale = [path for path in locale if path.exists()]
    token = [root / "packages/client/ui-theme/src/styles/design-platform.css"]
    layout = [
        root / "packages/client/ui-layout/src/client/columns.ts",
        root / "packages/client/ui-conversation/src/client/skeleton/ConversationRoot.module.css",
        root / "packages/client/ui-conversation/src/client/skeleton/InputBar.module.css",
        root / "packages/client/ui-workspace/src/client/WorkspaceBrowser.module.css",
    ]
    fixture = [
        root / "apps/web/tests/remote-welcome.e2e.ts",
        root / "apps/web/tests/support.ts",
        root / "packages/client/connection/src/client/fixture.ts",
    ]
    groups = {"locale": locale, "token": token, "layout": layout, "fixture": fixture}
    for name, paths in groups.items():
        missing = [path for path in paths if not path.exists()]
        if missing:
            raise SystemExit(f"{name} source(s) missing: {', '.join(str(path) for path in missing)}")
    return groups


def digest(paths: Iterable[Path], root: Path) -> tuple[str, list[dict[str, object]]]:
    accumulator = hashlib.sha256()
    entries: list[dict[str, object]] = []
    for path in sorted(paths):
        contents = path.read_bytes()
        file_hash = hashlib.sha256(contents).hexdigest()
        relative = path.relative_to(root).as_posix()
        accumulator.update(relative.encode("utf-8"))
        accumulator.update(b"\0")
        accumulator.update(contents)
        entries.append({"path": relative, "sha256": file_hash, "lines": contents.count(b"\n") + 1})
    return accumulator.hexdigest(), entries


def main() -> None:
    args = arguments()
    root = args.official_root.resolve()
    commit = git(root, "rev-parse", "HEAD")
    if commit != EXPECTED_COMMIT:
        raise SystemExit(f"official root must be {EXPECTED_COMMIT}, got {commit}")
    commit_time = git(root, "show", "-s", "--format=%cI", commit)
    groups = source_paths(root)
    revisions: dict[str, str] = {}
    inputs: list[dict[str, object]] = []
    for group, paths in groups.items():
        revision, entries = digest(paths, root)
        revisions[f"{group}Revision"] = f"sha256:{revision}"
        for entry in entries:
            entry["kind"] = group
            inputs.append(entry)
    metadata = {
        "schemaVersion": 1,
        "sourceCommit": commit,
        "hostBuildId": HOST_BUILD_ID,
        "uiSpecRevision": UI_SPEC_REVISION,
        **revisions,
        "generatedAt": commit_time,
        "generator": {"name": GENERATOR_NAME, "version": GENERATOR_VERSION},
        "inputs": sorted(inputs, key=lambda entry: (str(entry["kind"]), str(entry["path"]))),
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    swift = f'''// Generated by {GENERATOR_NAME} {GENERATOR_VERSION}; do not edit.\nimport Foundation\n\nextension OfficialUISpec {{\n    enum Build {{\n        static let id = "{HOST_BUILD_ID}"\n        static let sourceCommit = "{commit}"
        static let uiSpecRevision = "{UI_SPEC_REVISION}"
        static let localeRevision = "{metadata["localeRevision"]}"\n        static let tokenRevision = "{metadata["tokenRevision"]}"\n        static let layoutRevision = "{metadata["layoutRevision"]}"\n        static let fixtureRevision = "{metadata["fixtureRevision"]}"\n        static let generatedAt = "{commit_time}"\n        static let generatorVersion = "{GENERATOR_VERSION}"\n\n        static func isCompatible(with hostBuildID: String) -> Bool {{\n            hostBuildID == id\n        }}\n\n        static func requireCompatibility(with hostBuildID: String) {{\n            precondition(isCompatible(with: hostBuildID), "Official UI spec build \\(id) is incompatible with Host build \\(hostBuildID)")\n        }}\n    }}\n}}\n'''
    args.swift_output.parent.mkdir(parents=True, exist_ok=True)
    args.swift_output.write_text(swift, encoding="utf-8")
    print(f"Generated OfficialUISpec metadata for {commit}: {len(inputs)} upstream inputs.")


if __name__ == "__main__":
    main()
