#!/usr/bin/env python3
"""Generate a provenance-preserving English/Chinese locale catalog from locked upstream TypeScript."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
from collections import defaultdict
from pathlib import Path


GENERATOR_NAME = "generate_official_locales.py"
# Kept stable because it is stamped into the reproducible generated artifacts.
GENERATOR_VERSION = "1.0.0"
EXPECTED_COMMIT = "141eb6fef83422698aef7a981029e843e8161534"
AST_EXTRACTOR = Path(__file__).with_name("extract_official_locales_ast.mjs")


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--official-root", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--swift-output", type=Path, required=True)
    return parser.parse_args()


def git(root: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], text=True).strip()


def locale_files(root: Path) -> list[Path]:
    paths = set(root.glob("packages/client/**/src/client/locales.ts"))
    paths.update(root.glob("packages/client/**/src/client/locale.ts"))
    paths.update(root.glob("packages/client/locale/src/locales/*.ts"))
    return sorted(path for path in paths if path.is_file())


def locale_source_files(root: Path) -> list[Path]:
    paths = set(locale_files(root))
    paths.add(root / "packages/client/ui-settings-models/src/onboarding-copy.ts")
    missing = [path for path in paths if not path.is_file()]
    if missing:
        raise ValueError("missing locale source input(s): " + ", ".join(map(str, missing)))
    return sorted(paths)


def source_input_revision(root: Path) -> str:
    accumulator = hashlib.sha256()
    for path in locale_source_files(root):
        accumulator.update(path.relative_to(root).as_posix().encode("utf-8"))
        accumulator.update(b"\0")
        accumulator.update(path.read_bytes())
    return "sha256:" + accumulator.hexdigest()


def node_binary() -> str:
    """Use the locked Node 24 toolchain when the reference marker is available."""
    configured = os.environ.get("DSH_REFERENCE_NODE")
    if configured:
        return configured
    marker = Path("/home/ubuntu/reference/deepseek-harness/.reference-node-path")
    if marker.is_file():
        return str(Path(marker.read_text(encoding="utf-8").strip()) / "bin/node")
    return "node"


def parse_file(root: Path, path: Path, commit: str) -> list[dict[str, object]]:
    """Extract locale exports with the TypeScript compiler AST, never source-text matching."""
    process = subprocess.run(
        [node_binary(), str(AST_EXTRACTOR), str(root), str(path)],
        check=True,
        capture_output=True,
        text=True,
    )
    try:
        entries = json.loads(process.stdout)
    except json.JSONDecodeError as error:
        raise ValueError(f"AST locale extractor emitted invalid JSON for {path}") from error
    if not isinstance(entries, list):
        raise ValueError(f"AST locale extractor emitted a non-list result for {path}")
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError(f"AST locale extractor emitted a non-object entry for {path}")
        source = entry.get("source")
        if not isinstance(source, dict):
            raise ValueError(f"AST locale extractor entry lacks source provenance for {path}")
        source["commit"] = commit
    return entries


def revision(entries: list[dict[str, object]]) -> str:
    serial = json.dumps(entries, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(serial.encode("utf-8")).hexdigest()


def swift_source(entries: list[dict[str, object]], commit: str, locale_revision: str, source_input: str) -> str:
    values = {
        f"{entry['language']}|{entry['id']}": str(entry["value"])
        for entry in entries
    }
    body = ",\n".join(
        f"        {json.dumps(key, ensure_ascii=False)}: {json.dumps(value, ensure_ascii=False)}"
        for key, value in sorted(values.items())
    )
    return f'''// Generated by {GENERATOR_NAME} {GENERATOR_VERSION}; do not edit.\nimport Foundation\n\nextension OfficialUISpec {{\n    enum LocaleCatalog {{\n        static let sourceCommit = "{commit}"\n        static let revision = "{locale_revision}"\n        static let sourceInputRevision = "{source_input}"\n        static let supportedLanguages: Set<String> = ["en", "zh"]\n        static let values: [String: String] = [\n{body}\n        ]\n\n        static func contains(namespace: String, key: String, language: String) -> Bool {{\n            values["\\(language)|\\(namespace).\\(key)"] != nil\n        }}\n\n        static func value(namespace: String, key: String, language: String) -> String? {{\n            values["\\(language)|\\(namespace).\\(key)"]\n        }}\n    }}\n}}\n'''


def main() -> None:
    args = arguments()
    root = args.official_root.resolve()
    commit = git(root, "rev-parse", "HEAD")
    if commit != EXPECTED_COMMIT:
        raise SystemExit(f"official root must be {EXPECTED_COMMIT}, got {commit}")
    entries: list[dict[str, object]] = []
    for path in locale_files(root):
        entries.extend(parse_file(root, path, commit))
    if not entries:
        raise SystemExit("no locale entries found")
    entries.sort(key=lambda entry: (str(entry["namespace"]), str(entry["key"]), str(entry["language"])))
    unique = {(str(entry["id"]), str(entry["language"])) for entry in entries}
    if len(unique) != len(entries):
        raise SystemExit("duplicate namespace/key/language locale entry")
    languages = {str(entry["language"]) for entry in entries}
    if not {"en", "zh"}.issubset(languages):
        raise SystemExit("generated locale catalog must contain English and Chinese")
    by_key: dict[str, set[str]] = defaultdict(set)
    for entry in entries:
        by_key[str(entry["id"])].add(str(entry["language"]))
    incomplete = sorted(key for key, values in by_key.items() if not {"en", "zh"}.issubset(values))
    if incomplete:
        raise SystemExit("locale keys missing en/zh translation: " + ", ".join(incomplete[:20]))
    locale_revision = revision(entries)
    source_input = source_input_revision(root)
    metadata = {
        "schemaVersion": 1,
        "sourceCommit": commit,
        "localeRevision": locale_revision,
        "sourceInputRevision": source_input,
        "generatedAt": git(root, "show", "-s", "--format=%cI", commit),
        "generator": {"name": GENERATOR_NAME, "version": GENERATOR_VERSION},
        "languages": sorted(languages),
        "entries": entries,
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.swift_output.parent.mkdir(parents=True, exist_ok=True)
    args.swift_output.write_text(swift_source(entries, commit, locale_revision, source_input), encoding="utf-8")
    print(f"Generated {len(entries)} locale entries across {len(by_key)} keys from {len(locale_files(root))} files.")


if __name__ == "__main__":
    main()
