import Foundation

/// Generated by `generate_official_column_layout_fixtures.ts` through the locked
/// `packages/client/ui-layout/src/client/columns.ts` implementation.
struct OfficialColumnLayoutFixtureCatalog: Decodable {
    let schemaVersion: Int
    let sourceCommit: String
    let source: Source
    let generator: String
    let fixtures: [Fixture]

    struct Source: Decodable, Equatable {
        let path: String
        let sha256: String
    }

    struct Fixture: Decodable, Equatable {
        let name: String
        let viewport: CGFloat
        let sidebarPreference: CGFloat
        let detailsPreference: CGFloat
        let expected: Expected
    }

    struct Expected: Decodable, Equatable {
        let sidebar: CGFloat
        let center: CGFloat
        let details: CGFloat
    }

    static let lockedSourceCommit = "b150a551b8d465e31e418e1b2eaf5e79bbb7d28e"
    static let lockedSourcePath = "packages/client/ui-layout/src/client/columns.ts"
    static let lockedSourceSHA256 = "c2f002126fc671aeaad058eae310d265f7b1f9b77223686c0fe4619cda4e71e2"

    private static var resourceBundle: Bundle {
        #if SWIFT_PACKAGE
        .module
        #else
        .main
        #endif
    }

    static let catalog: OfficialColumnLayoutFixtureCatalog = {
        guard let url = resourceBundle.url(
            forResource: "official-column-layout-fixtures",
            withExtension: "json"
        ) else {
            preconditionFailure("Missing official column layout fixture resource")
        }
        do {
            let catalog = try JSONDecoder().decode(Self.self, from: Data(contentsOf: url))
            precondition(catalog.schemaVersion == 1, "Unsupported official column layout fixture schema")
            precondition(catalog.sourceCommit == lockedSourceCommit, "Official column layout fixture commit mismatch")
            precondition(catalog.source.path == lockedSourcePath, "Official column layout fixture source path mismatch")
            precondition(catalog.source.sha256 == lockedSourceSHA256, "Official column layout fixture source hash mismatch")
            precondition(!catalog.fixtures.isEmpty, "Official column layout fixture catalog is empty")
            return catalog
        } catch {
            preconditionFailure("Unable to decode official column layout fixtures: \(error)")
        }
    }()
}
