// Generated by generate_official_theme_tokens.py 1.0.0; do not edit.
import AppKit
import SwiftUI

struct OfficialRGBA: Hashable, Sendable {
    let red: Double
    let green: Double
    let blue: Double
    let alpha: Double

    func color(for scheme: ColorScheme) -> Color {
        Color(red: red, green: green, blue: blue, opacity: alpha)
    }
}

struct OfficialColorToken: Hashable, Sendable {
    let cssName: String
    let light: OfficialRGBA
    let dark: OfficialRGBA

    func color(for scheme: ColorScheme) -> Color {
        (scheme == .dark ? dark : light).color(for: scheme)
    }

    var lightColor: Color { light.color(for: .light) }
    var darkColor: Color { dark.color(for: .dark) }

    var adaptiveColor: Color {
        Color(NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
            let value = isDark ? dark : light
            return NSColor(srgbRed: value.red, green: value.green, blue: value.blue, alpha: value.alpha)
        })
    }
}

extension OfficialUISpec {
    enum Theme {
        static let sourceCommit = "528c682e061696f5a160f363f236ecbf53cbd006"
        static let revision = "sha256:7fbb81d2b7879c75c9fb6a9a5ec15435df9f916036fa925a70ca197a78bee42c"
        static let sourceInputRevision = "sha256:2d1743337b8fbba4bd052e8f1ecd24e490c2b5707faf8c185bfeae78fa702989"
        static let colorTokens: [String: OfficialColorToken] = [
        "--dsw-alias-bg-base": OfficialColorToken(cssName: "--dsw-alias-bg-base", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.08235294117647059, green: 0.08235294117647059, blue: 0.09019607843137255, alpha: 1)),
        "--dsw-alias-bg-layer-1": OfficialColorToken(cssName: "--dsw-alias-bg-layer-1", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.13725490196078433, green: 0.13725490196078433, blue: 0.1411764705882353, alpha: 1)),
        "--dsw-alias-bg-layer-2": OfficialColorToken(cssName: "--dsw-alias-bg-layer-2", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-alias-bg-layer-3": OfficialColorToken(cssName: "--dsw-alias-bg-layer-3", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-bg-mask-1": OfficialColorToken(cssName: "--dsw-alias-bg-mask-1", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.24), dark: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.5)),
        "--dsw-alias-bg-mask-2": OfficialColorToken(cssName: "--dsw-alias-bg-mask-2", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.12), dark: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.2)),
        "--dsw-alias-bg-mask-3": OfficialColorToken(cssName: "--dsw-alias-bg-mask-3", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.48), dark: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.48)),
        "--dsw-alias-bg-mask-drop": OfficialColorToken(cssName: "--dsw-alias-bg-mask-drop", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.7), dark: OfficialRGBA(red: 0.15294117647058825, green: 0.15294117647058825, blue: 0.18823529411764706, alpha: 0.7)),
        "--dsw-alias-bg-mask-photo": OfficialColorToken(cssName: "--dsw-alias-bg-mask-photo", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.88), dark: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.88)),
        "--dsw-alias-bg-module-platform": OfficialColorToken(cssName: "--dsw-alias-bg-module-platform", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9647058823529412, blue: 0.9686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-bg-multi-select": OfficialColorToken(cssName: "--dsw-alias-bg-multi-select", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9647058823529412, blue: 0.9686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.12941176470588237, green: 0.12941176470588237, blue: 0.13725490196078433, alpha: 1)),
        "--dsw-alias-bg-overlay": OfficialColorToken(cssName: "--dsw-alias-bg-overlay", light: OfficialRGBA(red: 0.9137254901960784, green: 0.9254901960784314, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.3803921568627451, green: 0.4, blue: 0.4196078431372549, alpha: 1)),
        "--dsw-alias-bg-skeleton": OfficialColorToken(cssName: "--dsw-alias-bg-skeleton", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.04), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.08)),
        "--dsw-alias-border-inverted": OfficialColorToken(cssName: "--dsw-alias-border-inverted", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.0), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.06)),
        "--dsw-alias-border-inverted2": OfficialColorToken(cssName: "--dsw-alias-border-inverted2", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.0), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.08)),
        "--dsw-alias-border-l1": OfficialColorToken(cssName: "--dsw-alias-border-l1", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.04), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.06)),
        "--dsw-alias-border-l2": OfficialColorToken(cssName: "--dsw-alias-border-l2", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.1), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.12)),
        "--dsw-alias-border-l2-darkmode-thin": OfficialColorToken(cssName: "--dsw-alias-border-l2-darkmode-thin", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.1), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.06)),
        "--dsw-alias-border-l3": OfficialColorToken(cssName: "--dsw-alias-border-l3", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.12), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.16)),
        "--dsw-alias-border-l4": OfficialColorToken(cssName: "--dsw-alias-border-l4", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 0.16), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.2)),
        "--dsw-alias-brand-primary": OfficialColorToken(cssName: "--dsw-alias-brand-primary", light: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-brand-primary-invert": OfficialColorToken(cssName: "--dsw-alias-brand-primary-invert", light: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-brand-primary-new-colorprimary-new-color": OfficialColorToken(cssName: "--dsw-alias-brand-primary-new-colorprimary-new-color", light: OfficialRGBA(red: 0.2549019607843137, green: 0.4627450980392157, blue: 0.9019607843137255, alpha: 1), dark: OfficialRGBA(red: 0.33725490196078434, green: 0.5254901960784314, blue: 0.996078431372549, alpha: 1)),
        "--dsw-alias-brand-text": OfficialColorToken(cssName: "--dsw-alias-brand-text", light: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-button-contrast-fill": OfficialColorToken(cssName: "--dsw-alias-button-contrast-fill", light: OfficialRGBA(red: 0.3803921568627451, green: 0.4, blue: 0.4196078431372549, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-button-elevated-fill": OfficialColorToken(cssName: "--dsw-alias-button-elevated-fill", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-alias-button-floating-fill": OfficialColorToken(cssName: "--dsw-alias-button-floating-fill", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-alias-button-floating-hover": OfficialColorToken(cssName: "--dsw-alias-button-floating-hover", light: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-button-ghost-active-border": OfficialColorToken(cssName: "--dsw-alias-button-ghost-active-border", light: OfficialRGBA(red: 0.592156862745098, green: 0.615686274509804, blue: 0.6509803921568628, alpha: 1), dark: OfficialRGBA(red: 0.5058823529411764, green: 0.5215686274509804, blue: 0.5490196078431373, alpha: 1)),
        "--dsw-alias-button-ghost-active-fill": OfficialColorToken(cssName: "--dsw-alias-button-ghost-active-fill", light: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-alias-button-ghost-active-hover": OfficialColorToken(cssName: "--dsw-alias-button-ghost-active-hover", light: OfficialRGBA(red: 0.9137254901960784, green: 0.9254901960784314, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.3803921568627451, green: 0.4, blue: 0.4196078431372549, alpha: 1)),
        "--dsw-alias-button-info-fill": OfficialColorToken(cssName: "--dsw-alias-button-info-fill", light: OfficialRGBA(red: 0.2549019607843137, green: 0.4627450980392157, blue: 0.9019607843137255, alpha: 1), dark: OfficialRGBA(red: 0.403921568627451, green: 0.6196078431372549, blue: 0.996078431372549, alpha: 1)),
        "--dsw-alias-button-info-hover": OfficialColorToken(cssName: "--dsw-alias-button-info-hover", light: OfficialRGBA(red: 0.403921568627451, green: 0.6196078431372549, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.2549019607843137, green: 0.4627450980392157, blue: 0.9019607843137255, alpha: 1)),
        "--dsw-alias-button-primary-dimmed": OfficialColorToken(cssName: "--dsw-alias-button-primary-dimmed", light: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-alias-button-primary-fill": OfficialColorToken(cssName: "--dsw-alias-button-primary-fill", light: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-button-primary-hover": OfficialColorToken(cssName: "--dsw-alias-button-primary-hover", light: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1), dark: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1)),
        "--dsw-alias-button-tool-bar-fill": OfficialColorToken(cssName: "--dsw-alias-button-tool-bar-fill", light: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 0.5), dark: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 0.5)),
        "--dsw-alias-button-tool-bar-fill-invisible": OfficialColorToken(cssName: "--dsw-alias-button-tool-bar-fill-invisible", light: OfficialRGBA(red: 0.12156862745098039, green: 0.12156862745098039, blue: 0.12156862745098039, alpha: 0.36), dark: OfficialRGBA(red: 0.12156862745098039, green: 0.12156862745098039, blue: 0.12156862745098039, alpha: 0.36)),
        "--dsw-alias-button-tool-bar-hover": OfficialColorToken(cssName: "--dsw-alias-button-tool-bar-hover", light: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 0.6), dark: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 0.6)),
        "--dsw-alias-interactive-bg-active": OfficialColorToken(cssName: "--dsw-alias-interactive-bg-active", light: OfficialRGBA(red: 0.14901960784313725, green: 0.19215686274509805, blue: 0.2823529411764706, alpha: 0.1), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.14)),
        "--dsw-alias-interactive-bg-hover": OfficialColorToken(cssName: "--dsw-alias-interactive-bg-hover", light: OfficialRGBA(red: 0.14901960784313725, green: 0.19215686274509805, blue: 0.2823529411764706, alpha: 0.06), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.08)),
        "--dsw-alias-interactive-bg-hover-accent": OfficialColorToken(cssName: "--dsw-alias-interactive-bg-hover-accent", light: OfficialRGBA(red: 0.14901960784313725, green: 0.19215686274509805, blue: 0.2823529411764706, alpha: 0.14), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 0.24)),
        "--dsw-alias-interactive-bg-hover-danger": OfficialColorToken(cssName: "--dsw-alias-interactive-bg-hover-danger", light: OfficialRGBA(red: 0.9254901960784314, green: 0.07450980392156863, blue: 0.07450980392156863, alpha: 0.05), dark: OfficialRGBA(red: 0.9490196078431372, green: 0.35294117647058826, blue: 0.35294117647058826, alpha: 0.15)),
        "--dsw-alias-interactive-bg-hover-solid": OfficialColorToken(cssName: "--dsw-alias-interactive-bg-hover-solid", light: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-label-caption": OfficialColorToken(cssName: "--dsw-alias-label-caption", light: OfficialRGBA(red: 0.6784313725490196, green: 0.6980392156862745, blue: 0.7215686274509804, alpha: 1), dark: OfficialRGBA(red: 0.5058823529411764, green: 0.5215686274509804, blue: 0.5490196078431373, alpha: 1)),
        "--dsw-alias-label-dimmed": OfficialColorToken(cssName: "--dsw-alias-label-dimmed", light: OfficialRGBA(red: 0.8823529411764706, green: 0.8980392156862745, blue: 0.9333333333333333, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-alias-label-primary": OfficialColorToken(cssName: "--dsw-alias-label-primary", light: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-label-primary-bluish": OfficialColorToken(cssName: "--dsw-alias-label-primary-bluish", light: OfficialRGBA(red: 0.054901960784313725, green: 0.18823529411764706, blue: 0.4549019607843137, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-alias-label-primary-dimmed": OfficialColorToken(cssName: "--dsw-alias-label-primary-dimmed", light: OfficialRGBA(red: 0.08235294117647059, green: 0.08235294117647059, blue: 0.09019607843137255, alpha: 1), dark: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1)),
        "--dsw-alias-label-primary-foreground": OfficialColorToken(cssName: "--dsw-alias-label-primary-foreground", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1)),
        "--dsw-alias-label-primary-inverted": OfficialColorToken(cssName: "--dsw-alias-label-primary-inverted", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-label-secondary": OfficialColorToken(cssName: "--dsw-alias-label-secondary", light: OfficialRGBA(red: 0.3803921568627451, green: 0.4, blue: 0.4196078431372549, alpha: 1), dark: OfficialRGBA(red: 0.8117647058823529, green: 0.8274509803921568, blue: 0.8392156862745098, alpha: 1)),
        "--dsw-alias-label-tertiary": OfficialColorToken(cssName: "--dsw-alias-label-tertiary", light: OfficialRGBA(red: 0.5058823529411764, green: 0.5215686274509804, blue: 0.5490196078431373, alpha: 1), dark: OfficialRGBA(red: 0.6784313725490196, green: 0.6980392156862745, blue: 0.7215686274509804, alpha: 1)),
        "--dsw-alias-markdown-citation": OfficialColorToken(cssName: "--dsw-alias-markdown-citation", light: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-markdown-code-block": OfficialColorToken(cssName: "--dsw-alias-markdown-code-block", light: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1), dark: OfficialRGBA(red: 0.10588235294117647, green: 0.10588235294117647, blue: 0.10980392156862745, alpha: 1)),
        "--dsw-alias-markdown-code-block-banner": OfficialColorToken(cssName: "--dsw-alias-markdown-code-block-banner", light: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-alias-markdown-code-segment-selected": OfficialColorToken(cssName: "--dsw-alias-markdown-code-segment-selected", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-alias-markdown-code-segment-unselected": OfficialColorToken(cssName: "--dsw-alias-markdown-code-segment-unselected", light: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.10588235294117647, green: 0.10588235294117647, blue: 0.10980392156862745, alpha: 1)),
        "--dsw-alias-markdown-inline-code": OfficialColorToken(cssName: "--dsw-alias-markdown-inline-code", light: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-alias-markdown-placeholder": OfficialColorToken(cssName: "--dsw-alias-markdown-placeholder", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9647058823529412, blue: 0.9686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-alias-markdown-tag": OfficialColorToken(cssName: "--dsw-alias-markdown-tag", light: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-alias-scrollbar-bg-l1": OfficialColorToken(cssName: "--dsw-alias-scrollbar-bg-l1", light: OfficialRGBA(red: 0.8980392156862745, green: 0.8980392156862745, blue: 0.8980392156862745, alpha: 1), dark: OfficialRGBA(red: 0.23529411764705882, green: 0.23529411764705882, blue: 0.23921568627450981, alpha: 1)),
        "--dsw-alias-scrollbar-bg-l2": OfficialColorToken(cssName: "--dsw-alias-scrollbar-bg-l2", light: OfficialRGBA(red: 0.8980392156862745, green: 0.8980392156862745, blue: 0.8980392156862745, alpha: 1), dark: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 1)),
        "--dsw-alias-scrollbar-hover-l1": OfficialColorToken(cssName: "--dsw-alias-scrollbar-hover-l1", light: OfficialRGBA(red: 0.8313725490196079, green: 0.8313725490196079, blue: 0.8313725490196079, alpha: 1), dark: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 1)),
        "--dsw-alias-scrollbar-hover-l2": OfficialColorToken(cssName: "--dsw-alias-scrollbar-hover-l2", light: OfficialRGBA(red: 0.8313725490196079, green: 0.8313725490196079, blue: 0.8313725490196079, alpha: 1), dark: OfficialRGBA(red: 0.396078431372549, green: 0.403921568627451, blue: 0.4196078431372549, alpha: 1)),
        "--dsw-alias-state-business-primary": OfficialColorToken(cssName: "--dsw-alias-state-business-primary", light: OfficialRGBA(red: 0.2549019607843137, green: 0.4627450980392157, blue: 0.9019607843137255, alpha: 1), dark: OfficialRGBA(red: 0.403921568627451, green: 0.6196078431372549, blue: 0.996078431372549, alpha: 1)),
        "--dsw-alias-state-business-tertiary": OfficialColorToken(cssName: "--dsw-alias-state-business-tertiary", light: OfficialRGBA(red: 0.8941176470588236, green: 0.9294117647058824, blue: 0.9921568627450981, alpha: 1), dark: OfficialRGBA(red: 0.20392156862745098, green: 0.2549019607843137, blue: 0.3568627450980392, alpha: 1)),
        "--dsw-alias-state-error-primary": OfficialColorToken(cssName: "--dsw-alias-state-error-primary", light: OfficialRGBA(red: 0.9254901960784314, green: 0.07450980392156863, blue: 0.07450980392156863, alpha: 1), dark: OfficialRGBA(red: 0.9490196078431372, green: 0.35294117647058826, blue: 0.35294117647058826, alpha: 1)),
        "--dsw-alias-state-error-secondary": OfficialColorToken(cssName: "--dsw-alias-state-error-secondary", light: OfficialRGBA(red: 0.9490196078431372, green: 0.35294117647058826, blue: 0.35294117647058826, alpha: 1), dark: OfficialRGBA(red: 0.9490196078431372, green: 0.35294117647058826, blue: 0.35294117647058826, alpha: 1)),
        "--dsw-alias-state-success-primary": OfficialColorToken(cssName: "--dsw-alias-state-success-primary", light: OfficialRGBA(red: 0.13333333333333333, green: 0.7725490196078432, blue: 0.3686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.13333333333333333, green: 0.7725490196078432, blue: 0.3686274509803922, alpha: 1)),
        "--dsw-alias-state-success-secondary": OfficialColorToken(cssName: "--dsw-alias-state-success-secondary", light: OfficialRGBA(red: 0.3058823529411765, green: 0.8196078431372549, blue: 0.49411764705882355, alpha: 1), dark: OfficialRGBA(red: 0.3058823529411765, green: 0.8196078431372549, blue: 0.49411764705882355, alpha: 1)),
        "--dsw-alias-state-success-tertiary": OfficialColorToken(cssName: "--dsw-alias-state-success-tertiary", light: OfficialRGBA(red: 0.9019607843137255, green: 0.9803921568627451, blue: 0.9294117647058824, alpha: 1), dark: OfficialRGBA(red: 0.13725490196078433, green: 0.23529411764705882, blue: 0.17254901960784313, alpha: 1)),
        "--dsw-alias-state-warn-label": OfficialColorToken(cssName: "--dsw-alias-state-warn-label", light: OfficialRGBA(red: 0.8666666666666667, green: 0.5254901960784314, blue: 0.1607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.8666666666666667, green: 0.5254901960784314, blue: 0.1607843137254902, alpha: 1)),
        "--dsw-alias-state-warn-primary": OfficialColorToken(cssName: "--dsw-alias-state-warn-primary", light: OfficialRGBA(red: 0.9607843137254902, green: 0.6196078431372549, blue: 0.043137254901960784, alpha: 1), dark: OfficialRGBA(red: 0.9607843137254902, green: 0.6196078431372549, blue: 0.043137254901960784, alpha: 1)),
        "--dsw-alias-state-warn-secondary": OfficialColorToken(cssName: "--dsw-alias-state-warn-secondary", light: OfficialRGBA(red: 0.9686274509803922, green: 0.6784313725490196, blue: 0.19215686274509805, alpha: 1), dark: OfficialRGBA(red: 0.9686274509803922, green: 0.6784313725490196, blue: 0.19215686274509805, alpha: 1)),
        "--dsw-alias-state-warn-tertiary": OfficialColorToken(cssName: "--dsw-alias-state-warn-tertiary", light: OfficialRGBA(red: 0.996078431372549, green: 0.9607843137254902, blue: 0.9058823529411765, alpha: 1), dark: OfficialRGBA(red: 0.15294117647058825, green: 0.1411764705882353, blue: 0.12156862745098039, alpha: 1)),
        "--dsw-alias-toast-bg": OfficialColorToken(cssName: "--dsw-alias-toast-bg", light: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-alias-tooltip-bg": OfficialColorToken(cssName: "--dsw-alias-tooltip-bg", light: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-specific-bubble": OfficialColorToken(cssName: "--dsw-specific-bubble", light: OfficialRGBA(red: 0.9294117647058824, green: 0.9529411764705882, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-specific-bubble-highlight": OfficialColorToken(cssName: "--dsw-specific-bubble-highlight", light: OfficialRGBA(red: 0.8274509803921568, green: 0.8862745098039215, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-specific-input-major": OfficialColorToken(cssName: "--dsw-specific-input-major", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-specific-login-input": OfficialColorToken(cssName: "--dsw-specific-login-input", light: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1), dark: OfficialRGBA(red: 0.10588235294117647, green: 0.10588235294117647, blue: 0.10980392156862745, alpha: 1)),
        "--dsw-specific-menu": OfficialColorToken(cssName: "--dsw-specific-menu", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-specific-selector": OfficialColorToken(cssName: "--dsw-specific-selector", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9647058823529412, blue: 0.9686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-specific-sidebar-fill": OfficialColorToken(cssName: "--dsw-specific-sidebar-fill", light: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1), dark: OfficialRGBA(red: 0.10588235294117647, green: 0.10588235294117647, blue: 0.10980392156862745, alpha: 1)),
        "--dsw-specific-sidebar-nav-item-active": OfficialColorToken(cssName: "--dsw-specific-sidebar-nav-item-active", light: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-specific-sidebar-nav-item-active-accent": OfficialColorToken(cssName: "--dsw-specific-sidebar-nav-item-active-accent", light: OfficialRGBA(red: 0.8941176470588236, green: 0.9294117647058824, blue: 0.9921568627450981, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-specific-sidebar-nav-item-hover": OfficialColorToken(cssName: "--dsw-specific-sidebar-nav-item-hover", light: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-specific-tip": OfficialColorToken(cssName: "--dsw-specific-tip", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9647058823529412, blue: 0.9686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-static-amber-100": OfficialColorToken(cssName: "--dsw-static-amber-100", light: OfficialRGBA(red: 0.996078431372549, green: 0.9607843137254902, blue: 0.9058823529411765, alpha: 1), dark: OfficialRGBA(red: 0.996078431372549, green: 0.9607843137254902, blue: 0.9058823529411765, alpha: 1)),
        "--dsw-static-amber-400": OfficialColorToken(cssName: "--dsw-static-amber-400", light: OfficialRGBA(red: 0.9686274509803922, green: 0.6784313725490196, blue: 0.19215686274509805, alpha: 1), dark: OfficialRGBA(red: 0.9686274509803922, green: 0.6784313725490196, blue: 0.19215686274509805, alpha: 1)),
        "--dsw-static-amber-500": OfficialColorToken(cssName: "--dsw-static-amber-500", light: OfficialRGBA(red: 0.9607843137254902, green: 0.6196078431372549, blue: 0.043137254901960784, alpha: 1), dark: OfficialRGBA(red: 0.9607843137254902, green: 0.6196078431372549, blue: 0.043137254901960784, alpha: 1)),
        "--dsw-static-amber-600": OfficialColorToken(cssName: "--dsw-static-amber-600", light: OfficialRGBA(red: 0.8666666666666667, green: 0.5254901960784314, blue: 0.1607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.8666666666666667, green: 0.5254901960784314, blue: 0.1607843137254902, alpha: 1)),
        "--dsw-static-amber-900": OfficialColorToken(cssName: "--dsw-static-amber-900", light: OfficialRGBA(red: 0.15294117647058825, green: 0.1411764705882353, blue: 0.12156862745098039, alpha: 1), dark: OfficialRGBA(red: 0.15294117647058825, green: 0.1411764705882353, blue: 0.12156862745098039, alpha: 1)),
        "--dsw-static-blue-100": OfficialColorToken(cssName: "--dsw-static-blue-100", light: OfficialRGBA(red: 0.8588235294117647, green: 0.9176470588235294, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.8588235294117647, green: 0.9176470588235294, blue: 0.996078431372549, alpha: 1)),
        "--dsw-static-blue-300": OfficialColorToken(cssName: "--dsw-static-blue-300", light: OfficialRGBA(red: 0.5764705882352941, green: 0.7725490196078432, blue: 0.9921568627450981, alpha: 1), dark: OfficialRGBA(red: 0.5764705882352941, green: 0.7725490196078432, blue: 0.9921568627450981, alpha: 1)),
        "--dsw-static-blue-400": OfficialColorToken(cssName: "--dsw-static-blue-400", light: OfficialRGBA(red: 0.3764705882352941, green: 0.6470588235294118, blue: 0.9803921568627451, alpha: 1), dark: OfficialRGBA(red: 0.3764705882352941, green: 0.6470588235294118, blue: 0.9803921568627451, alpha: 1)),
        "--dsw-static-blue-450": OfficialColorToken(cssName: "--dsw-static-blue-450", light: OfficialRGBA(red: 0.30196078431372547, green: 0.5764705882352941, blue: 0.9725490196078431, alpha: 1), dark: OfficialRGBA(red: 0.30196078431372547, green: 0.5764705882352941, blue: 0.9725490196078431, alpha: 1)),
        "--dsw-static-blue-50": OfficialColorToken(cssName: "--dsw-static-blue-50", light: OfficialRGBA(red: 0.9372549019607843, green: 0.9647058823529412, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.9372549019607843, green: 0.9647058823529412, blue: 1.0, alpha: 1)),
        "--dsw-static-blue-500": OfficialColorToken(cssName: "--dsw-static-blue-500", light: OfficialRGBA(red: 0.23137254901960785, green: 0.5098039215686274, blue: 0.9647058823529412, alpha: 1), dark: OfficialRGBA(red: 0.23137254901960785, green: 0.5098039215686274, blue: 0.9647058823529412, alpha: 1)),
        "--dsw-static-blue-50p": OfficialColorToken(cssName: "--dsw-static-blue-50p", light: OfficialRGBA(red: 0.9176470588235294, green: 0.9529411764705882, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.9176470588235294, green: 0.9529411764705882, blue: 1.0, alpha: 1)),
        "--dsw-static-blue-600": OfficialColorToken(cssName: "--dsw-static-blue-600", light: OfficialRGBA(red: 0.1450980392156863, green: 0.38823529411764707, blue: 0.9215686274509803, alpha: 1), dark: OfficialRGBA(red: 0.1450980392156863, green: 0.38823529411764707, blue: 0.9215686274509803, alpha: 1)),
        "--dsw-static-blue-75": OfficialColorToken(cssName: "--dsw-static-blue-75", light: OfficialRGBA(red: 0.8980392156862745, green: 0.9411764705882353, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.8980392156862745, green: 0.9411764705882353, blue: 1.0, alpha: 1)),
        "--dsw-static-blue-800": OfficialColorToken(cssName: "--dsw-static-blue-800", light: OfficialRGBA(red: 0.11764705882352941, green: 0.25098039215686274, blue: 0.6862745098039216, alpha: 1), dark: OfficialRGBA(red: 0.11764705882352941, green: 0.25098039215686274, blue: 0.6862745098039216, alpha: 1)),
        "--dsw-static-blue-900": OfficialColorToken(cssName: "--dsw-static-blue-900", light: OfficialRGBA(red: 0.054901960784313725, green: 0.18823529411764706, blue: 0.4549019607843137, alpha: 1), dark: OfficialRGBA(red: 0.054901960784313725, green: 0.18823529411764706, blue: 0.4549019607843137, alpha: 1)),
        "--dsw-static-blue-950": OfficialColorToken(cssName: "--dsw-static-blue-950", light: OfficialRGBA(red: 0.09019607843137255, green: 0.1450980392156863, blue: 0.32941176470588235, alpha: 1), dark: OfficialRGBA(red: 0.09019607843137255, green: 0.1450980392156863, blue: 0.32941176470588235, alpha: 1)),
        "--dsw-static-deepseek-100": OfficialColorToken(cssName: "--dsw-static-deepseek-100", light: OfficialRGBA(red: 0.8941176470588236, green: 0.9294117647058824, blue: 0.9921568627450981, alpha: 1), dark: OfficialRGBA(red: 0.8941176470588236, green: 0.9294117647058824, blue: 0.9921568627450981, alpha: 1)),
        "--dsw-static-deepseek-200": OfficialColorToken(cssName: "--dsw-static-deepseek-200", light: OfficialRGBA(red: 0.8274509803921568, green: 0.8862745098039215, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 0.8274509803921568, green: 0.8862745098039215, blue: 1.0, alpha: 1)),
        "--dsw-static-deepseek-300": OfficialColorToken(cssName: "--dsw-static-deepseek-300", light: OfficialRGBA(red: 0.7176470588235294, green: 0.7843137254901961, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.7176470588235294, green: 0.7843137254901961, blue: 0.996078431372549, alpha: 1)),
        "--dsw-static-deepseek-400": OfficialColorToken(cssName: "--dsw-static-deepseek-400", light: OfficialRGBA(red: 0.403921568627451, green: 0.6196078431372549, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.403921568627451, green: 0.6196078431372549, blue: 0.996078431372549, alpha: 1)),
        "--dsw-static-deepseek-450": OfficialColorToken(cssName: "--dsw-static-deepseek-450", light: OfficialRGBA(red: 0.33725490196078434, green: 0.5254901960784314, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.33725490196078434, green: 0.5254901960784314, blue: 0.996078431372549, alpha: 1)),
        "--dsw-static-deepseek-50": OfficialColorToken(cssName: "--dsw-static-deepseek-50", light: OfficialRGBA(red: 0.9294117647058824, green: 0.9529411764705882, blue: 0.996078431372549, alpha: 1), dark: OfficialRGBA(red: 0.9294117647058824, green: 0.9529411764705882, blue: 0.996078431372549, alpha: 1)),
        "--dsw-static-deepseek-500": OfficialColorToken(cssName: "--dsw-static-deepseek-500", light: OfficialRGBA(red: 0.2549019607843137, green: 0.4627450980392157, blue: 0.9019607843137255, alpha: 1), dark: OfficialRGBA(red: 0.2549019607843137, green: 0.4627450980392157, blue: 0.9019607843137255, alpha: 1)),
        "--dsw-static-deepseek-600": OfficialColorToken(cssName: "--dsw-static-deepseek-600", light: OfficialRGBA(red: 0.2823529411764706, green: 0.40784313725490196, blue: 0.6980392156862745, alpha: 1), dark: OfficialRGBA(red: 0.2823529411764706, green: 0.40784313725490196, blue: 0.6980392156862745, alpha: 1)),
        "--dsw-static-deepseek-700-delete": OfficialColorToken(cssName: "--dsw-static-deepseek-700-delete", light: OfficialRGBA(red: 0.1843137254901961, green: 0.2980392156862745, blue: 0.5607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.1843137254901961, green: 0.2980392156862745, blue: 0.5607843137254902, alpha: 1)),
        "--dsw-static-deepseek-800": OfficialColorToken(cssName: "--dsw-static-deepseek-800", light: OfficialRGBA(red: 0.20392156862745098, green: 0.2549019607843137, blue: 0.3568627450980392, alpha: 1), dark: OfficialRGBA(red: 0.20392156862745098, green: 0.2549019607843137, blue: 0.3568627450980392, alpha: 1)),
        "--dsw-static-deepseek-900": OfficialColorToken(cssName: "--dsw-static-deepseek-900", light: OfficialRGBA(red: 0.1568627450980392, green: 0.19215686274509805, blue: 0.25882352941176473, alpha: 1), dark: OfficialRGBA(red: 0.1568627450980392, green: 0.19215686274509805, blue: 0.25882352941176473, alpha: 1)),
        "--dsw-static-green-100": OfficialColorToken(cssName: "--dsw-static-green-100", light: OfficialRGBA(red: 0.9019607843137255, green: 0.9803921568627451, blue: 0.9294117647058824, alpha: 1), dark: OfficialRGBA(red: 0.9019607843137255, green: 0.9803921568627451, blue: 0.9294117647058824, alpha: 1)),
        "--dsw-static-green-400": OfficialColorToken(cssName: "--dsw-static-green-400", light: OfficialRGBA(red: 0.3058823529411765, green: 0.8196078431372549, blue: 0.49411764705882355, alpha: 1), dark: OfficialRGBA(red: 0.3058823529411765, green: 0.8196078431372549, blue: 0.49411764705882355, alpha: 1)),
        "--dsw-static-green-500": OfficialColorToken(cssName: "--dsw-static-green-500", light: OfficialRGBA(red: 0.13333333333333333, green: 0.7725490196078432, blue: 0.3686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.13333333333333333, green: 0.7725490196078432, blue: 0.3686274509803922, alpha: 1)),
        "--dsw-static-green-900": OfficialColorToken(cssName: "--dsw-static-green-900", light: OfficialRGBA(red: 0.13725490196078433, green: 0.23529411764705882, blue: 0.17254901960784313, alpha: 1), dark: OfficialRGBA(red: 0.13725490196078433, green: 0.23529411764705882, blue: 0.17254901960784313, alpha: 1)),
        "--dsw-static-neutral-00": OfficialColorToken(cssName: "--dsw-static-neutral-00", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)),
        "--dsw-static-neutral-100": OfficialColorToken(cssName: "--dsw-static-neutral-100", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9607843137254902, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.9607843137254902, green: 0.9607843137254902, blue: 0.9607843137254902, alpha: 1)),
        "--dsw-static-neutral-1000": OfficialColorToken(cssName: "--dsw-static-neutral-1000", light: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 1), dark: OfficialRGBA(red: 0.0, green: 0.0, blue: 0.0, alpha: 1)),
        "--dsw-static-neutral-150": OfficialColorToken(cssName: "--dsw-static-neutral-150", light: OfficialRGBA(red: 0.9294117647058824, green: 0.9294117647058824, blue: 0.9294117647058824, alpha: 1), dark: OfficialRGBA(red: 0.9294117647058824, green: 0.9294117647058824, blue: 0.9294117647058824, alpha: 1)),
        "--dsw-static-neutral-200": OfficialColorToken(cssName: "--dsw-static-neutral-200", light: OfficialRGBA(red: 0.8980392156862745, green: 0.8980392156862745, blue: 0.8980392156862745, alpha: 1), dark: OfficialRGBA(red: 0.8980392156862745, green: 0.8980392156862745, blue: 0.8980392156862745, alpha: 1)),
        "--dsw-static-neutral-250": OfficialColorToken(cssName: "--dsw-static-neutral-250", light: OfficialRGBA(red: 0.8627450980392157, green: 0.8627450980392157, blue: 0.8627450980392157, alpha: 1), dark: OfficialRGBA(red: 0.8627450980392157, green: 0.8627450980392157, blue: 0.8627450980392157, alpha: 1)),
        "--dsw-static-neutral-300": OfficialColorToken(cssName: "--dsw-static-neutral-300", light: OfficialRGBA(red: 0.8313725490196079, green: 0.8313725490196079, blue: 0.8313725490196079, alpha: 1), dark: OfficialRGBA(red: 0.8313725490196079, green: 0.8313725490196079, blue: 0.8313725490196079, alpha: 1)),
        "--dsw-static-neutral-400": OfficialColorToken(cssName: "--dsw-static-neutral-400", light: OfficialRGBA(red: 0.6352941176470588, green: 0.6431372549019608, blue: 0.6509803921568628, alpha: 1), dark: OfficialRGBA(red: 0.6352941176470588, green: 0.6431372549019608, blue: 0.6509803921568628, alpha: 1)),
        "--dsw-static-neutral-50": OfficialColorToken(cssName: "--dsw-static-neutral-50", light: OfficialRGBA(red: 0.9803921568627451, green: 0.9803921568627451, blue: 0.9803921568627451, alpha: 1), dark: OfficialRGBA(red: 0.9803921568627451, green: 0.9803921568627451, blue: 0.9803921568627451, alpha: 1)),
        "--dsw-static-neutral-500": OfficialColorToken(cssName: "--dsw-static-neutral-500", light: OfficialRGBA(red: 0.4980392156862745, green: 0.5098039215686274, blue: 0.5294117647058824, alpha: 1), dark: OfficialRGBA(red: 0.4980392156862745, green: 0.5098039215686274, blue: 0.5294117647058824, alpha: 1)),
        "--dsw-static-neutral-550": OfficialColorToken(cssName: "--dsw-static-neutral-550", light: OfficialRGBA(red: 0.396078431372549, green: 0.403921568627451, blue: 0.4196078431372549, alpha: 1), dark: OfficialRGBA(red: 0.396078431372549, green: 0.403921568627451, blue: 0.4196078431372549, alpha: 1)),
        "--dsw-static-neutral-600": OfficialColorToken(cssName: "--dsw-static-neutral-600", light: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 1), dark: OfficialRGBA(red: 0.32941176470588235, green: 0.3333333333333333, blue: 0.3411764705882353, alpha: 1)),
        "--dsw-static-neutral-700": OfficialColorToken(cssName: "--dsw-static-neutral-700", light: OfficialRGBA(red: 0.23529411764705882, green: 0.23529411764705882, blue: 0.23921568627450981, alpha: 1), dark: OfficialRGBA(red: 0.23529411764705882, green: 0.23529411764705882, blue: 0.23921568627450981, alpha: 1)),
        "--dsw-static-neutral-800": OfficialColorToken(cssName: "--dsw-static-neutral-800", light: OfficialRGBA(red: 0.1607843137254902, green: 0.1607843137254902, blue: 0.1607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.1607843137254902, green: 0.1607843137254902, blue: 0.1607843137254902, alpha: 1)),
        "--dsw-static-neutral-850": OfficialColorToken(cssName: "--dsw-static-neutral-850", light: OfficialRGBA(red: 0.12941176470588237, green: 0.12941176470588237, blue: 0.13725490196078433, alpha: 1), dark: OfficialRGBA(red: 0.12941176470588237, green: 0.12941176470588237, blue: 0.13725490196078433, alpha: 1)),
        "--dsw-static-neutral-900": OfficialColorToken(cssName: "--dsw-static-neutral-900", light: OfficialRGBA(red: 0.058823529411764705, green: 0.058823529411764705, blue: 0.058823529411764705, alpha: 1), dark: OfficialRGBA(red: 0.058823529411764705, green: 0.058823529411764705, blue: 0.058823529411764705, alpha: 1)),
        "--dsw-static-neutral-bluish-00": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-00", light: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1), dark: OfficialRGBA(red: 1.0, green: 1.0, blue: 1.0, alpha: 1)),
        "--dsw-static-neutral-bluish-100": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-100", light: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.9215686274509803, green: 0.9333333333333333, blue: 0.9490196078431372, alpha: 1)),
        "--dsw-static-neutral-bluish-1000": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-1000", light: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1), dark: OfficialRGBA(red: 0.058823529411764705, green: 0.06666666666666667, blue: 0.08235294117647059, alpha: 1)),
        "--dsw-static-neutral-bluish-150": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-150", light: OfficialRGBA(red: 0.9137254901960784, green: 0.9254901960784314, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.9137254901960784, green: 0.9254901960784314, blue: 0.9490196078431372, alpha: 1)),
        "--dsw-static-neutral-bluish-200": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-200", light: OfficialRGBA(red: 0.8823529411764706, green: 0.8980392156862745, blue: 0.9333333333333333, alpha: 1), dark: OfficialRGBA(red: 0.8823529411764706, green: 0.8980392156862745, blue: 0.9333333333333333, alpha: 1)),
        "--dsw-static-neutral-bluish-300": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-300", light: OfficialRGBA(red: 0.8117647058823529, green: 0.8274509803921568, blue: 0.8392156862745098, alpha: 1), dark: OfficialRGBA(red: 0.8117647058823529, green: 0.8274509803921568, blue: 0.8392156862745098, alpha: 1)),
        "--dsw-static-neutral-bluish-400": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-400", light: OfficialRGBA(red: 0.6784313725490196, green: 0.6980392156862745, blue: 0.7215686274509804, alpha: 1), dark: OfficialRGBA(red: 0.6784313725490196, green: 0.6980392156862745, blue: 0.7215686274509804, alpha: 1)),
        "--dsw-static-neutral-bluish-50": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-50", light: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-static-neutral-bluish-500": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-500", light: OfficialRGBA(red: 0.592156862745098, green: 0.615686274509804, blue: 0.6509803921568628, alpha: 1), dark: OfficialRGBA(red: 0.592156862745098, green: 0.615686274509804, blue: 0.6509803921568628, alpha: 1)),
        "--dsw-static-neutral-bluish-60": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-60", light: OfficialRGBA(red: 0.9607843137254902, green: 0.9647058823529412, blue: 0.9686274509803922, alpha: 1), dark: OfficialRGBA(red: 0.9764705882352941, green: 0.9803921568627451, blue: 0.984313725490196, alpha: 1)),
        "--dsw-static-neutral-bluish-600": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-600", light: OfficialRGBA(red: 0.5058823529411764, green: 0.5215686274509804, blue: 0.5490196078431373, alpha: 1), dark: OfficialRGBA(red: 0.5058823529411764, green: 0.5215686274509804, blue: 0.5490196078431373, alpha: 1)),
        "--dsw-static-neutral-bluish-700": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-700", light: OfficialRGBA(red: 0.3803921568627451, green: 0.4, blue: 0.4196078431372549, alpha: 1), dark: OfficialRGBA(red: 0.3803921568627451, green: 0.4, blue: 0.4196078431372549, alpha: 1)),
        "--dsw-static-neutral-bluish-75": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-75", light: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1), dark: OfficialRGBA(red: 0.9450980392156862, green: 0.9529411764705882, blue: 0.9607843137254902, alpha: 1)),
        "--dsw-static-neutral-bluish-750": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-750", light: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1), dark: OfficialRGBA(red: 0.2627450980392157, green: 0.27058823529411763, blue: 0.2901960784313726, alpha: 1)),
        "--dsw-static-neutral-bluish-800": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-800", light: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1), dark: OfficialRGBA(red: 0.20784313725490197, green: 0.21176470588235294, blue: 0.2196078431372549, alpha: 1)),
        "--dsw-static-neutral-bluish-850": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-850", light: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1), dark: OfficialRGBA(red: 0.17254901960784313, green: 0.17254901960784313, blue: 0.1803921568627451, alpha: 1)),
        "--dsw-static-neutral-bluish-875": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-875", light: OfficialRGBA(red: 0.13725490196078433, green: 0.13725490196078433, blue: 0.1411764705882353, alpha: 1), dark: OfficialRGBA(red: 0.13725490196078433, green: 0.13725490196078433, blue: 0.1411764705882353, alpha: 1)),
        "--dsw-static-neutral-bluish-900": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-900", light: OfficialRGBA(red: 0.10588235294117647, green: 0.10588235294117647, blue: 0.10980392156862745, alpha: 1), dark: OfficialRGBA(red: 0.10588235294117647, green: 0.10588235294117647, blue: 0.10980392156862745, alpha: 1)),
        "--dsw-static-neutral-bluish-950": OfficialColorToken(cssName: "--dsw-static-neutral-bluish-950", light: OfficialRGBA(red: 0.08235294117647059, green: 0.08235294117647059, blue: 0.09019607843137255, alpha: 1), dark: OfficialRGBA(red: 0.08235294117647059, green: 0.08235294117647059, blue: 0.09019607843137255, alpha: 1)),
        "--dsw-static-red-100": OfficialColorToken(cssName: "--dsw-static-red-100", light: OfficialRGBA(red: 0.996078431372549, green: 0.8862745098039215, blue: 0.8862745098039215, alpha: 1), dark: OfficialRGBA(red: 0.996078431372549, green: 0.8862745098039215, blue: 0.8862745098039215, alpha: 1)),
        "--dsw-static-red-400": OfficialColorToken(cssName: "--dsw-static-red-400", light: OfficialRGBA(red: 0.9490196078431372, green: 0.35294117647058826, blue: 0.35294117647058826, alpha: 1), dark: OfficialRGBA(red: 0.9490196078431372, green: 0.35294117647058826, blue: 0.35294117647058826, alpha: 1)),
        "--dsw-static-red-50": OfficialColorToken(cssName: "--dsw-static-red-50", light: OfficialRGBA(red: 0.996078431372549, green: 0.9490196078431372, blue: 0.9490196078431372, alpha: 1), dark: OfficialRGBA(red: 0.996078431372549, green: 0.9490196078431372, blue: 0.9490196078431372, alpha: 1)),
        "--dsw-static-red-500": OfficialColorToken(cssName: "--dsw-static-red-500", light: OfficialRGBA(red: 0.9372549019607843, green: 0.26666666666666666, blue: 0.26666666666666666, alpha: 1), dark: OfficialRGBA(red: 0.9372549019607843, green: 0.26666666666666666, blue: 0.26666666666666666, alpha: 1)),
        "--dsw-static-red-600": OfficialColorToken(cssName: "--dsw-static-red-600", light: OfficialRGBA(red: 0.9254901960784314, green: 0.07450980392156863, blue: 0.07450980392156863, alpha: 1), dark: OfficialRGBA(red: 0.9254901960784314, green: 0.07450980392156863, blue: 0.07450980392156863, alpha: 1)),
        "--dsw-static-red-900": OfficialColorToken(cssName: "--dsw-static-red-900", light: OfficialRGBA(red: 0.3411764705882353, green: 0.047058823529411764, blue: 0.047058823529411764, alpha: 1), dark: OfficialRGBA(red: 0.3411764705882353, green: 0.047058823529411764, blue: 0.047058823529411764, alpha: 1))
        ]

        static func value(_ cssName: String) -> OfficialColorToken {
            guard let token = colorTokens[cssName] else {
                preconditionFailure("Unknown official color token: \(cssName)")
            }
            return token
        }

    static let aliasBgBase = value("--dsw-alias-bg-base")
    static let aliasBgLayer1 = value("--dsw-alias-bg-layer-1")
    static let aliasBgLayer2 = value("--dsw-alias-bg-layer-2")
    static let aliasBgLayer3 = value("--dsw-alias-bg-layer-3")
    static let aliasBgMask1 = value("--dsw-alias-bg-mask-1")
    static let aliasBgMask2 = value("--dsw-alias-bg-mask-2")
    static let aliasBgMask3 = value("--dsw-alias-bg-mask-3")
    static let aliasBgMaskDrop = value("--dsw-alias-bg-mask-drop")
    static let aliasBgMaskPhoto = value("--dsw-alias-bg-mask-photo")
    static let aliasBgModulePlatform = value("--dsw-alias-bg-module-platform")
    static let aliasBgMultiSelect = value("--dsw-alias-bg-multi-select")
    static let aliasBgOverlay = value("--dsw-alias-bg-overlay")
    static let aliasBgSkeleton = value("--dsw-alias-bg-skeleton")
    static let aliasBorderInverted = value("--dsw-alias-border-inverted")
    static let aliasBorderInverted2 = value("--dsw-alias-border-inverted2")
    static let aliasBorderL1 = value("--dsw-alias-border-l1")
    static let aliasBorderL2 = value("--dsw-alias-border-l2")
    static let aliasBorderL2DarkmodeThin = value("--dsw-alias-border-l2-darkmode-thin")
    static let aliasBorderL3 = value("--dsw-alias-border-l3")
    static let aliasBorderL4 = value("--dsw-alias-border-l4")
    static let aliasBrandPrimary = value("--dsw-alias-brand-primary")
    static let aliasBrandPrimaryInvert = value("--dsw-alias-brand-primary-invert")
    static let aliasBrandPrimaryNewColorprimaryNewColor = value("--dsw-alias-brand-primary-new-colorprimary-new-color")
    static let aliasBrandText = value("--dsw-alias-brand-text")
    static let aliasButtonContrastFill = value("--dsw-alias-button-contrast-fill")
    static let aliasButtonElevatedFill = value("--dsw-alias-button-elevated-fill")
    static let aliasButtonFloatingFill = value("--dsw-alias-button-floating-fill")
    static let aliasButtonFloatingHover = value("--dsw-alias-button-floating-hover")
    static let aliasButtonGhostActiveBorder = value("--dsw-alias-button-ghost-active-border")
    static let aliasButtonGhostActiveFill = value("--dsw-alias-button-ghost-active-fill")
    static let aliasButtonGhostActiveHover = value("--dsw-alias-button-ghost-active-hover")
    static let aliasButtonInfoFill = value("--dsw-alias-button-info-fill")
    static let aliasButtonInfoHover = value("--dsw-alias-button-info-hover")
    static let aliasButtonPrimaryDimmed = value("--dsw-alias-button-primary-dimmed")
    static let aliasButtonPrimaryFill = value("--dsw-alias-button-primary-fill")
    static let aliasButtonPrimaryHover = value("--dsw-alias-button-primary-hover")
    static let aliasButtonToolBarFill = value("--dsw-alias-button-tool-bar-fill")
    static let aliasButtonToolBarFillInvisible = value("--dsw-alias-button-tool-bar-fill-invisible")
    static let aliasButtonToolBarHover = value("--dsw-alias-button-tool-bar-hover")
    static let aliasInteractiveBgActive = value("--dsw-alias-interactive-bg-active")
    static let aliasInteractiveBgHover = value("--dsw-alias-interactive-bg-hover")
    static let aliasInteractiveBgHoverAccent = value("--dsw-alias-interactive-bg-hover-accent")
    static let aliasInteractiveBgHoverDanger = value("--dsw-alias-interactive-bg-hover-danger")
    static let aliasInteractiveBgHoverSolid = value("--dsw-alias-interactive-bg-hover-solid")
    static let aliasLabelCaption = value("--dsw-alias-label-caption")
    static let aliasLabelDimmed = value("--dsw-alias-label-dimmed")
    static let aliasLabelPrimary = value("--dsw-alias-label-primary")
    static let aliasLabelPrimaryBluish = value("--dsw-alias-label-primary-bluish")
    static let aliasLabelPrimaryDimmed = value("--dsw-alias-label-primary-dimmed")
    static let aliasLabelPrimaryForeground = value("--dsw-alias-label-primary-foreground")
    static let aliasLabelPrimaryInverted = value("--dsw-alias-label-primary-inverted")
    static let aliasLabelSecondary = value("--dsw-alias-label-secondary")
    static let aliasLabelTertiary = value("--dsw-alias-label-tertiary")
    static let aliasMarkdownCitation = value("--dsw-alias-markdown-citation")
    static let aliasMarkdownCodeBlock = value("--dsw-alias-markdown-code-block")
    static let aliasMarkdownCodeBlockBanner = value("--dsw-alias-markdown-code-block-banner")
    static let aliasMarkdownCodeSegmentSelected = value("--dsw-alias-markdown-code-segment-selected")
    static let aliasMarkdownCodeSegmentUnselected = value("--dsw-alias-markdown-code-segment-unselected")
    static let aliasMarkdownInlineCode = value("--dsw-alias-markdown-inline-code")
    static let aliasMarkdownPlaceholder = value("--dsw-alias-markdown-placeholder")
    static let aliasMarkdownTag = value("--dsw-alias-markdown-tag")
    static let aliasScrollbarBgL1 = value("--dsw-alias-scrollbar-bg-l1")
    static let aliasScrollbarBgL2 = value("--dsw-alias-scrollbar-bg-l2")
    static let aliasScrollbarHoverL1 = value("--dsw-alias-scrollbar-hover-l1")
    static let aliasScrollbarHoverL2 = value("--dsw-alias-scrollbar-hover-l2")
    static let aliasStateBusinessPrimary = value("--dsw-alias-state-business-primary")
    static let aliasStateBusinessTertiary = value("--dsw-alias-state-business-tertiary")
    static let aliasStateErrorPrimary = value("--dsw-alias-state-error-primary")
    static let aliasStateErrorSecondary = value("--dsw-alias-state-error-secondary")
    static let aliasStateSuccessPrimary = value("--dsw-alias-state-success-primary")
    static let aliasStateSuccessSecondary = value("--dsw-alias-state-success-secondary")
    static let aliasStateSuccessTertiary = value("--dsw-alias-state-success-tertiary")
    static let aliasStateWarnLabel = value("--dsw-alias-state-warn-label")
    static let aliasStateWarnPrimary = value("--dsw-alias-state-warn-primary")
    static let aliasStateWarnSecondary = value("--dsw-alias-state-warn-secondary")
    static let aliasStateWarnTertiary = value("--dsw-alias-state-warn-tertiary")
    static let aliasToastBg = value("--dsw-alias-toast-bg")
    static let aliasTooltipBg = value("--dsw-alias-tooltip-bg")
    static let specificBubble = value("--dsw-specific-bubble")
    static let specificBubbleHighlight = value("--dsw-specific-bubble-highlight")
    static let specificInputMajor = value("--dsw-specific-input-major")
    static let specificLoginInput = value("--dsw-specific-login-input")
    static let specificMenu = value("--dsw-specific-menu")
    static let specificSelector = value("--dsw-specific-selector")
    static let specificSidebarFill = value("--dsw-specific-sidebar-fill")
    static let specificSidebarNavItemActive = value("--dsw-specific-sidebar-nav-item-active")
    static let specificSidebarNavItemActiveAccent = value("--dsw-specific-sidebar-nav-item-active-accent")
    static let specificSidebarNavItemHover = value("--dsw-specific-sidebar-nav-item-hover")
    static let specificTip = value("--dsw-specific-tip")
    static let staticAmber100 = value("--dsw-static-amber-100")
    static let staticAmber400 = value("--dsw-static-amber-400")
    static let staticAmber500 = value("--dsw-static-amber-500")
    static let staticAmber600 = value("--dsw-static-amber-600")
    static let staticAmber900 = value("--dsw-static-amber-900")
    static let staticBlue100 = value("--dsw-static-blue-100")
    static let staticBlue300 = value("--dsw-static-blue-300")
    static let staticBlue400 = value("--dsw-static-blue-400")
    static let staticBlue450 = value("--dsw-static-blue-450")
    static let staticBlue50 = value("--dsw-static-blue-50")
    static let staticBlue500 = value("--dsw-static-blue-500")
    static let staticBlue50p = value("--dsw-static-blue-50p")
    static let staticBlue600 = value("--dsw-static-blue-600")
    static let staticBlue75 = value("--dsw-static-blue-75")
    static let staticBlue800 = value("--dsw-static-blue-800")
    static let staticBlue900 = value("--dsw-static-blue-900")
    static let staticBlue950 = value("--dsw-static-blue-950")
    static let staticDeepseek100 = value("--dsw-static-deepseek-100")
    static let staticDeepseek200 = value("--dsw-static-deepseek-200")
    static let staticDeepseek300 = value("--dsw-static-deepseek-300")
    static let staticDeepseek400 = value("--dsw-static-deepseek-400")
    static let staticDeepseek450 = value("--dsw-static-deepseek-450")
    static let staticDeepseek50 = value("--dsw-static-deepseek-50")
    static let staticDeepseek500 = value("--dsw-static-deepseek-500")
    static let staticDeepseek600 = value("--dsw-static-deepseek-600")
    static let staticDeepseek700Delete = value("--dsw-static-deepseek-700-delete")
    static let staticDeepseek800 = value("--dsw-static-deepseek-800")
    static let staticDeepseek900 = value("--dsw-static-deepseek-900")
    static let staticGreen100 = value("--dsw-static-green-100")
    static let staticGreen400 = value("--dsw-static-green-400")
    static let staticGreen500 = value("--dsw-static-green-500")
    static let staticGreen900 = value("--dsw-static-green-900")
    static let staticNeutral00 = value("--dsw-static-neutral-00")
    static let staticNeutral100 = value("--dsw-static-neutral-100")
    static let staticNeutral1000 = value("--dsw-static-neutral-1000")
    static let staticNeutral150 = value("--dsw-static-neutral-150")
    static let staticNeutral200 = value("--dsw-static-neutral-200")
    static let staticNeutral250 = value("--dsw-static-neutral-250")
    static let staticNeutral300 = value("--dsw-static-neutral-300")
    static let staticNeutral400 = value("--dsw-static-neutral-400")
    static let staticNeutral50 = value("--dsw-static-neutral-50")
    static let staticNeutral500 = value("--dsw-static-neutral-500")
    static let staticNeutral550 = value("--dsw-static-neutral-550")
    static let staticNeutral600 = value("--dsw-static-neutral-600")
    static let staticNeutral700 = value("--dsw-static-neutral-700")
    static let staticNeutral800 = value("--dsw-static-neutral-800")
    static let staticNeutral850 = value("--dsw-static-neutral-850")
    static let staticNeutral900 = value("--dsw-static-neutral-900")
    static let staticNeutralBluish00 = value("--dsw-static-neutral-bluish-00")
    static let staticNeutralBluish100 = value("--dsw-static-neutral-bluish-100")
    static let staticNeutralBluish1000 = value("--dsw-static-neutral-bluish-1000")
    static let staticNeutralBluish150 = value("--dsw-static-neutral-bluish-150")
    static let staticNeutralBluish200 = value("--dsw-static-neutral-bluish-200")
    static let staticNeutralBluish300 = value("--dsw-static-neutral-bluish-300")
    static let staticNeutralBluish400 = value("--dsw-static-neutral-bluish-400")
    static let staticNeutralBluish50 = value("--dsw-static-neutral-bluish-50")
    static let staticNeutralBluish500 = value("--dsw-static-neutral-bluish-500")
    static let staticNeutralBluish60 = value("--dsw-static-neutral-bluish-60")
    static let staticNeutralBluish600 = value("--dsw-static-neutral-bluish-600")
    static let staticNeutralBluish700 = value("--dsw-static-neutral-bluish-700")
    static let staticNeutralBluish75 = value("--dsw-static-neutral-bluish-75")
    static let staticNeutralBluish750 = value("--dsw-static-neutral-bluish-750")
    static let staticNeutralBluish800 = value("--dsw-static-neutral-bluish-800")
    static let staticNeutralBluish850 = value("--dsw-static-neutral-bluish-850")
    static let staticNeutralBluish875 = value("--dsw-static-neutral-bluish-875")
    static let staticNeutralBluish900 = value("--dsw-static-neutral-bluish-900")
    static let staticNeutralBluish950 = value("--dsw-static-neutral-bluish-950")
    static let staticRed100 = value("--dsw-static-red-100")
    static let staticRed400 = value("--dsw-static-red-400")
    static let staticRed50 = value("--dsw-static-red-50")
    static let staticRed500 = value("--dsw-static-red-500")
    static let staticRed600 = value("--dsw-static-red-600")
    static let staticRed900 = value("--dsw-static-red-900")
    }
}
